### ISSUE TITLE
Lighting issue after coming out of dungeon.

### ISSUE THREAD

**Issue by jtylerr** [Toliann/Nyx#1]
Before going into the dungeon, lighting is bright and normal like it should be. I've tested multiple times and it seems when you go in and then go out the lighting will just go pitch black except for the lights placed (the sky turns black and no lighting from the sun). I use with Scoopys Castle Interior, not sure if that could cause conflicts with the planets lighting. I am also getting errors in logs about Reverb.Audio but i'll assume thats nothing major.

**Comment by Toliann** [comment]
Fixed in the new version
