### ISSUE TITLE
Interior de-sync when playing with friends

### ISSUE THREAD

**Issue by jtylerr** [Toliann/Nyx#3]
certain doors will not be on certain players clients, certain walls will be able to be walked through by certain players, sometimes some players will just completely fall out of the map and die. does not happen on Vanilla planets happens on all maps i have installed which are Nyx and Crystallum.

**Comment by Toliann** [comment]
I've been notified of this problem, and I'm in the process of fixing it

**Comment by Toliann** [comment]
Try the latest version, if the problem appears, then upload here the logs of the host and those who had this happen (this will help me determine the problem in more detail)

**Comment by jtylerr** [comment]
> Try the latest version, if the problem appears, then upload here the logs of the host and those who had this happen (this will help me determine the problem in more detail)

will do

**Comment by Toliann** [comment]
Is desynchronization still happening?

**Comment by Toliann** [comment]
Fixed in the latest update
